// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiTFz5j2u3Q9iUvLLiud7MgtWk0FyQ1L0',
    appId: '1:914396480458:web:83bdded6b8410b88318533',
    messagingSenderId: '914396480458',
    projectId: 'onclick-69f84',
    authDomain: 'onclick-69f84.firebaseapp.com',
    storageBucket: 'onclick-69f84.firebasestorage.app',
    measurementId: 'G-ZDB1M200MX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVlVhphq4LxBOPVEhkikIsdhEZPA2gKD4',
    appId: '1:914396480458:android:d8eed8f01a0fd4a7318533',
    messagingSenderId: '914396480458',
    projectId: 'onclick-69f84',
    storageBucket: 'onclick-69f84.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBchx048Fs-tuBfKJKLCBgQgOwKIHg2ZT4',
    appId: '1:914396480458:ios:e92e5009114f9fe5318533',
    messagingSenderId: '914396480458',
    projectId: 'onclick-69f84',
    storageBucket: 'onclick-69f84.firebasestorage.app',
    iosBundleId: 'com.tienda.onclickapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBchx048Fs-tuBfKJKLCBgQgOwKIHg2ZT4',
    appId: '1:914396480458:ios:e92e5009114f9fe5318533',
    messagingSenderId: '914396480458',
    projectId: 'onclick-69f84',
    storageBucket: 'onclick-69f84.firebasestorage.app',
    iosBundleId: 'com.tienda.onclickapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCiTFz5j2u3Q9iUvLLiud7MgtWk0FyQ1L0',
    appId: '1:914396480458:web:bd9b3f03b1f6abdc318533',
    messagingSenderId: '914396480458',
    projectId: 'onclick-69f84',
    authDomain: 'onclick-69f84.firebaseapp.com',
    storageBucket: 'onclick-69f84.firebasestorage.app',
    measurementId: 'G-L96MJE4W9Q',
  );

}